version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - shawnkoon
  assignees:
  - shawnkoon
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.4
    - 2.8.1
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: autopep8
    versions:
    - 1.5.5
